(autoload 'ruby-mode "ruby-mode" nil t)
(add-to-list 'auto-mode-alist '("Capfile" . ruby-mode))
(add-to-list 'auto-mode-alist '("Gemfile" . ruby-mode))
(add-to-list 'auto-mode-alist '("Rakefile" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.rake\\'" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.rb\\'" . ruby-mode))
(add-to-list 'auto-mode-alist '("\\.ru\\'" . ruby-mode))
(add-hook 'ruby-mode-hook '(lambda ()
                             (setq ruby-deep-arglist t)
                             (setq ruby-deep-indent-paren nil)
                             (setq c-tab-always-indent nil)
                             (require 'inf-ruby)
                             (require 'ruby-compilation)))
;; (defun rhtml-mode-hook ()
;;   (autoload 'rhtml-mode "rhtml-mode" nil t)
;;   (add-to-list 'auto-mode-alist '("\\.erb\\'" . rhtml-mode))
;;   (add-to-list 'auto-mode-alist '("\\.rjs\\'" . rhtml-mode))
;;   (add-hook 'rhtml-mode '(lambda ()
;;                            (define-key rhtml-mode-map (kbd "M-s") 'save-buffer))))
;; (defun yaml-mode-hook ()
;;   (autoload 'yaml-mode "yaml-mode" nil t)
;;   (add-to-list 'auto-mode-alist '("\\.yml$" . yaml-mode))
;;   (add-to-list 'auto-mode-alist '("\\.yaml$" . yaml-mode)))
;; (defun css-mode-hook ()
;;   (autoload 'css-mode "css-mode" nil t)
;;   (add-hook 'css-mode-hook '(lambda ()
;;                               (setq css-indent-level 2)
;;                               (setq css-indent-offset 2))))

;; (add-to-list 'inf-ruby-implementations '("pry" . "pry"))
;; (setq inf-ruby-default-implementation "/home/lianyijiang/.rvm/gems/ruby-1.9.3-p194@myrails3/bin/pry")
;; (setq inf-ruby-first-prompt-pattern "^\\[[0-9]+\\] pry\\((.*)\\)> *")
;; (setq inf-ruby-prompt-pattern "^\\[[0-9]+\\] pry\\((.*)\\)[>*\"'] *")

;; (autoload 'inf-ruby "inf-ruby" "Run an inferior Ruby process" t)
;; (autoload 'inf-ruby-setup-keybindings "inf-ruby" "" t)
;; (eval-after-load 'ruby-mode
;;   '(add-hook 'ruby-mode-hook 'inf-ruby-setup-keybindings))
